[package]
name = "ascii_opengl_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.32.1"
image = "0.24.6"
terminal_size = "0.2.6"
device_query = "1.1.3"
